
name: deploy software engineering

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: checkout repo
      uses: actions/checkout@v1

    - name: build static html
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        make html

    - name: copy to academis server 
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.ACADEMIS_HOST }}
        username: ${{ secrets.ACADEMIS_USERNAME }}
        port: 22
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: build/html/*
        target: /www/academis/software_engineering
        rm: true
        strip_components: 2
